[versions]
accompanist = "0.37.3"
activity = "1.11.0"
agp = "8.13.1"
baselineprofile = "1.2.3"
camera = "1.4.0-SNAPSHOT"
coil = "2.7.0"
compose_bom = "2025.11.00"
concurrent = "1.1.0"
core = "1.17.0"
core-splashscreen = "1.0.1"
espresso = "3.5.1"
graphics = "1.0.0-alpha05"
hilt = "2.57.2"
hiltNavigationCompose = "1.3.0"
junit = "4.13.2"
kotlin = "2.2.0"
ksp = "2.2.0-2.0.2"
lifecycle = "2.9.4"
material3 = "1.4.0"
navigation = "2.8.0-alpha07"
profileinstaller = "1.3.1"
room = "2.8.3"
spotless = "6.24.0"
test = "1.1.5"
truth = "1.1.3"
turbine = "1.0.0"
window = "1.2.0"
material3-adaptive-navigation-suite = "1.0.0-alpha05"
glance = "1.1.0-alpha01"
secrets = "2.0.1"
generativeai = "0.7.0"
datastore = "1.1.7"
navigation3UiAndroid = "1.0.0-rc01"

[libraries]
accompanist-painter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
camera-extensions = { group = "androidx.camera", name = "camera-extensions", version.ref = "camera" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose_bom" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
compose-material3-adaptive = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "material3-adaptive-navigation-suite"}
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-test-manisfest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
concurrent-kts = { group = "androidx.concurrent", name = "concurrent-futures-ktx", version.ref = "concurrent" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "test" }
glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }
glance-material = { group = "androidx.glance", name = "glance-material3", version.ref = "glance" }
graphics-shapes = { group = "androidx.graphics", name = "graphics-shapes", version.ref = "graphics" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
window = { group = "androidx.window", name = "window", version.ref = "window" }
generativeai = { group = "com.google.ai.client.generativeai", name = "generativeai", version.ref = "generativeai"}
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore"}
navigation3-ui-android = { group = "androidx.navigation3", name = "navigation3-ui-android", version.ref = "navigation3UiAndroid" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidTest = { id = "com.android.test", version.ref = "agp" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }
